CREATE TABLE EMPLOYEES.EMPLOYEE(
    ID          BIGINT IDENTITY(1,1) NOT NULL,
    FIRST_NAME  NVARCHAR(255) NOT NULL,
    LAST_NAME   NVARCHAR(255) NOT NULL,
    EMAIL       VARCHAR(255) NOT NULL,
    DEPARTMENT  VARCHAR(255) NULL,
    SALARY      NUMERIC(19,6),

    CREATED_BY          VARCHAR(255),
    CREATION_DATE       DATETIME2,
    SOFT_DELETED        BIT NOT NULL,
    MODIFICATION_DATE   DATETIME2,
    MODIFIED_BY         VARCHAR(255),

    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ID)
)